### PR TITLE
add forwarding common events

### PR DESCRIPTION
**Pull request by PaulMaly**

### CODE REVIEW

**Comment by blokhin** [comment]
@Valexr why there are so many events mentioned?

**Comment by Valexr** [comment]
Why Valexr, it’s not my PR? 😁 but I think it’s for future usability

**Comment by blokhin** [comment]
@Valexr thx, just asking

**Comment by PaulMaly** [comment]
@blokhin to make them available directly on component’s tag. Svelte doesn’t have automatic events forwarding. Bubbling is not so convenient and clean, also some events doesn’t support bubbling. Actually I forwarded not all events supported by select element but these is most common and useful in my opinion.

**Pull request merged**
